"""Generate every table and every inline number in the paper from result files.

Nothing in the LaTeX is typed by hand. `main.tex` includes `tables/*.tex` and
`tables/numbers.tex`, so re-running this after more sweep runs land updates the
prose and the tables together and they cannot drift apart.

    python paper/neurips2026_workshop/make_tables.py \
        --classical results/classical/classical_benchmark.json \
        --pinn results/pinn --ablation results/pinn_ablation \
        --outdir paper/neurips2026_workshop/tables
"""
import argparse
import json
from collections import defaultdict
from pathlib import Path

MATERIALS = ["Homogeneous", "TwoLayer", "MultiLayer"]
METHOD_LABEL = {"fd2": "\\texttt{fd2} (FD2)", "fem_p1": "\\texttt{fem\\_p1} (P1 FEM)",
                "cheb": "\\texttt{cheb} (spectral)"}
ARCH_ORDER = ["PINN", "FourierFeaturePINN", "PirateNet", "KAN", "WavKAN",
              "ChebyshevKAN", "FourierWavKAN"]
ARCH_LABEL = {"PINN": "VanillaPINN", "FourierFeaturePINN": "FourierFeature",
              "PirateNet": "PirateNet", "KAN": "KAN (spline)",
              "WavKAN": "WavKAN", "ChebyshevKAN": "ChebyshevKAN",
              "FourierWavKAN": "FourierWavKAN"}


def fmt_err(v):
    """Percent error, at a precision that does not imply false significance."""
    if v is None:
        return "--"
    if v >= 100:
        return f"{v:.0f}"
    if v >= 10:
        return f"{v:.1f}"
    if v >= 1:
        return f"{v:.2f}"
    if v >= 0.01:
        return f"{v:.3f}"
    if v == 0.0:
        return "$<10^{-5}$"
    return f"{v:.1e}".replace("e-0", "e{-}").replace("e-", "e{-}")


def fmt_secs(v):
    if v is None:
        return "--"
    if v >= 100:
        return f"{v:.0f}"
    if v >= 1:
        return f"{v:.2f}"
    return f"{v:.4f}"


# ------------------------------------------------------------------ classical

def classical_tables(data, out):
    conv = data["convergence"]
    by = defaultdict(dict)
    for r in conv:
        by[(r["material"], r["method"])][r["n"]] = r

    # Table 1: what it costs to reach a target accuracy, and where the method
    # stops improving. Cost-to-target is the number a practitioner acts on;
    # the smallest error on a ladder is not, because for the spectral solver it
    # is just the reference's own precision.
    def cheapest_below(rows, target):
        ok = [r for r in rows.values() if r["rel_l2_percent"] <= target]
        return min(ok, key=lambda r: r["seconds"]) if ok else None

    def cell(r):
        if r is None:
            return "\\textit{n/a} & --"
        return f"{r['n']} & {fmt_secs(r['seconds'])}"

    lines = [
        "% generated by make_tables.py -- do not edit",
        "\\begin{table}[t]",
        "\\centering",
        "\\caption{Cost of accuracy for the three classical discretisations, "
        "measured against a converged spectral solution. Each pair of columns "
        "gives the cheapest resolution on the refinement ladder that reaches the "
        "target and the wall-clock seconds it took (best of three, one CPU core). "
        "\\textit{n/a} means no resolution on the ladder reaches it. "
        "\\textbf{Floor} is where the method stops improving: the two "
        "second-order schemes stall at the same $0.04\\%$ on all three materials, "
        "which is the first-order Mur absorbing boundary rather than the interior "
        "stencil.}",
        "\\label{tab:classical}",
        "\\small",
        "\\begin{tabular}{llrrrrrrr}",
        "\\toprule",
        " & & \\multicolumn{2}{c}{$\\leq 1\\%$} & \\multicolumn{2}{c}{$\\leq 0.1\\%$}"
        " & \\multicolumn{2}{c}{$\\leq 0.01\\%$} & floor \\\\",
        "\\cmidrule(lr){3-4}\\cmidrule(lr){5-6}\\cmidrule(lr){7-8}\\cmidrule(lr){9-9}",
        "material & method & $n$ & s & $n$ & s & $n$ & s & \\% \\\\",
        "\\midrule",
    ]
    for mat in MATERIALS:
        first = True
        for method in ("fd2", "fem_p1", "cheb"):
            rows = by[(mat, method)]
            if not rows:
                continue
            floor = min(r["rel_l2_percent"] for r in rows.values())
            # A spectral solver measured against a spectral reference bottoms
            # out at the reference's precision; report that as such.
            floor_s = ("$\\approx$ ref." if floor < 1e-8
                       else fmt_err(floor))
            label = f"\\multirow{{3}}{{*}}{{{mat}}}" if first else ""
            first = False
            lines.append(
                f"{label} & {METHOD_LABEL[method]} & "
                f"{cell(cheapest_below(rows, 1.0))} & "
                f"{cell(cheapest_below(rows, 0.1))} & "
                f"{cell(cheapest_below(rows, 0.01))} & {floor_s} \\\\")
        lines.append("\\midrule" if mat != MATERIALS[-1] else "\\bottomrule")
    lines += ["\\end{tabular}", "\\end{table}", ""]
    (out / "classical.tex").write_text("\n".join(lines))

    # Table 2: the reference solver's own error at the resolution the PINN
    # runs score against.
    lines = [
        "% generated by make_tables.py -- do not edit",
        "\\begin{table}[t]",
        "\\centering",
        "\\caption{The finite-difference reference the PINN runs are scored "
        "against, measured against converged spectral ground truth. Refinement "
        "stops paying at roughly $N_x = 1600$; beyond that the error is set by "
        "the first-order absorbing boundary. $N_x = 1000$ is the setting the "
        "sweep uses.}",
        "\\label{tab:reffloor}",
        "\\small",
        "\\begin{tabular}{lrrrrrr}",
        "\\toprule",
        "material & \\multicolumn{6}{c}{relative $L^2$ (\\%) of \\texttt{fd2} at $N_x$} \\\\",
        "\\cmidrule(lr){2-7}",
        " & 250 & 500 & \\textbf{1000} & 2000 & 4000 & 8000 \\\\",
        "\\midrule",
    ]
    ref = defaultdict(dict)
    for r in data["pinn_reference_error"]:
        ref[r["material"]][r["nx"]] = r["rel_l2_percent"]
    for mat in MATERIALS:
        cells = " & ".join(fmt_err(ref[mat].get(nx))
                           for nx in (250, 500, 1000, 2000, 4000, 8000))
        lines.append(f"{mat} & {cells} \\\\")
    lines += ["\\bottomrule", "\\end{tabular}", "\\end{table}", ""]
    (out / "reffloor.tex").write_text("\n".join(lines))

    numbers = {}
    # Cheapest spectral run that beats the second-order floor by 10x, per
    # material. Quoting the smallest number on the ladder would be quoting the
    # reference's own precision, not an error.
    for mat in MATERIALS:
        rows = by[(mat, "cheb")]
        if not rows:
            continue
        good = [r for r in rows.values() if r["rel_l2_percent"] < 4e-3]
        pick = min(good, key=lambda r: r["seconds"]) if good else \
            min(rows.values(), key=lambda r: r["rel_l2_percent"])
        numbers[f"Cheb{mat}Err"] = fmt_err(pick["rel_l2_percent"])
        numbers[f"Cheb{mat}Secs"] = fmt_secs(pick["seconds"])
        numbers[f"Cheb{mat}N"] = str(pick["n"])

    fd_floor = [r["rel_l2_percent"] for (m, meth), rows in by.items()
                if meth in ("fd2", "fem_p1") for r in rows.values()]
    if fd_floor:
        numbers["FDFloor"] = fmt_err(min(fd_floor))
    ref = defaultdict(dict)
    for r in data["pinn_reference_error"]:
        ref[r["material"]][r["nx"]] = r
    if ref["Homogeneous"]:
        numbers["FDRefErr"] = fmt_err(ref["Homogeneous"][1000]["rel_l2_percent"])
        numbers["FDRefSecs"] = fmt_secs(
            max(ref[m][1000]["seconds"] for m in MATERIALS if ref[m]))
    for r in data["reference_self_convergence"]:
        numbers[f"RefSelfConv{r['material']}"] = (
            f"{r['rel_l2_percent']:.1e}".replace("e-", "e{-}"))
    return numbers


# ----------------------------------------------------------------------- pinn

def load_pinn(root):
    """Collect every l2_errors.json under `root` into flat records."""
    out = []
    root = Path(root)
    if not root.exists():
        return out
    for path in sorted(root.rglob("l2_errors.json")):
        d = json.loads(path.read_text())
        d["_dir"] = path.parent.name
        d["_material"] = d.get("material_type") or path.parent.parent.name
        best = None
        for key in ("relative_l2_error_best_lbfgs_percent",
                    "relative_l2_error_best_lbfgs_only_percent",
                    "relative_l2_error_best_adam_percent"):
            if key in d and d[key] is not None:
                best = d[key] if best is None else min(best, d[key])
        d["_best"] = best
        out.append(d)
    return out


def variant_of(rec):
    if rec.get("optimizer") == "lbfgs_only":
        return "lbfgs_only"
    tag = []
    if rec.get("optimizer") == "soap":
        tag.append("soap")
    if rec.get("weighting") == "rba":
        tag.append("rba")
    return "+".join(tag) if tag else "base"


def pinn_tables(records, out):
    numbers = {}
    if not records:
        (out / "pinn_main.tex").write_text(
            "% no PINN results found yet -- rerun make_tables.py after the sweep\n")
        (out / "pinn_variants.tex").write_text("")
        numbers["PinnRunCount"] = "0"
        return numbers

    base = [r for r in records if variant_of(r) == "base"]
    grid = defaultdict(dict)
    for r in base:
        grid[(r["model_type"], r["_material"])][bool(r["use_ansatz"])] = r["_best"]

    lines = [
        "% generated by make_tables.py -- do not edit",
        "\\begin{table}[t]",
        "\\centering",
        "\\caption{Coordinate networks under the published recipe (causal "
        "weighting + GradNorm, Adam then L-BFGS). Relative $L^2$ (\\%) against "
        "the finite-difference reference, taking the better reported Adam or "
        "L-BFGS checkpoint; "
        "\\textbf{hard} is the constraint "
        "ansatz, \\textbf{soft} the IC loss. A zero field scores $\\approx100$. "
        "For scale, the classical column of Table~\\ref{tab:classical} reaches "
        "$0.04\\%$ in under \\SI{20}{\\milli\\second}.}",
        "\\label{tab:pinnmain}",
        "\\small",
        "\\begin{tabular}{l" + "rr" * len(MATERIALS) + "}",
        "\\toprule",
        " & " + " & ".join(f"\\multicolumn{{2}}{{c}}{{{m}}}" for m in MATERIALS)
        + " \\\\",
        " ".join(f"\\cmidrule(lr){{{2 + 2 * i}-{3 + 2 * i}}}"
                 for i in range(len(MATERIALS))),
        "architecture & " + " & ".join(["hard & soft"] * len(MATERIALS)) + " \\\\",
        "\\midrule",
    ]
    for arch in ARCH_ORDER:
        cells = []
        for mat in MATERIALS:
            g = grid.get((arch, mat), {})
            cells += [fmt_err(g.get(True)), fmt_err(g.get(False))]
        if any(c != "--" for c in cells):
            lines.append(f"{ARCH_LABEL[arch]} & " + " & ".join(cells) + " \\\\")
    lines += ["\\bottomrule", "\\end{tabular}", "\\end{table}", ""]
    (out / "pinn_main.tex").write_text("\n".join(lines))

    # Variant arms (SOAP / RBA / L-BFGS-only) against their own base config.
    var = defaultdict(dict)
    for r in records:
        if not r.get("use_ansatz"):
            continue
        var[(r["model_type"], r["_material"])][variant_of(r)] = r["_best"]
    cols = ["base", "soap", "rba", "soap+rba", "lbfgs_only"]
    collabel = {"base": "base", "soap": "SOAP", "rba": "RBA",
                "soap+rba": "SOAP+RBA", "lbfgs\\_only": "L-BFGS only"}
    lines = [
        "% generated by make_tables.py -- do not edit",
        "\\begin{table}[t]",
        "\\centering",
        "\\caption{Variant training arms, hard-constraint IC, relative $L^2$ "
        "(\\%) at the better reported first- or second-order checkpoint. SOAP "
        "replaces Adam; RBA replaces causal weighting with "
        "residual-based attention; L-BFGS-only removes the first-order phase "
        "entirely.}",
        "\\label{tab:pinnvariants}",
        "\\small",
        "\\begin{tabular}{ll" + "r" * len(cols) + "}",
        "\\toprule",
        "material & architecture & "
        + " & ".join(collabel.get(c, c.replace("_", "\\_")) for c in cols) + " \\\\",
        "\\midrule",
    ]
    any_row = False
    for mat in MATERIALS:
        for arch in ARCH_ORDER:
            row = var.get((arch, mat), {})
            if not any(c in row for c in cols[1:]):
                continue
            cells = " & ".join(fmt_err(row.get(c)) for c in cols)
            lines.append(f"{mat} & {ARCH_LABEL[arch]} & {cells} \\\\")
            any_row = True
    lines += ["\\bottomrule", "\\end{tabular}", "\\end{table}", ""]
    (out / "pinn_variants.tex").write_text("\n".join(lines) if any_row else "")

    finite = [r["_best"] for r in records if r["_best"] is not None]
    numbers["PinnRunCount"] = str(len(records))
    if finite:
        numbers["PinnBestErr"] = fmt_err(min(finite))
        numbers["PinnMedianErr"] = fmt_err(sorted(finite)[len(finite) // 2])
        numbers["PinnAboveHundred"] = str(sum(1 for v in finite if v >= 100))
    # The published recipe on its own, excluding the SOAP/RBA/L-BFGS-only arms.
    # The ablation is a comparison against *this*, so the abstract must quote it
    # rather than the best number anywhere in the sweep -- the sweep's best is
    # an RBA run, which has already removed causal weighting.
    recipe = [r["_best"] for r in base if r["_best"] is not None]
    if recipe:
        numbers["PinnRecipeBestErr"] = fmt_err(min(recipe))
        numbers["PinnRecipeAboveHundred"] = str(sum(1 for v in recipe if v >= 100))
        numbers["PinnRecipeCount"] = str(len(recipe))
    rba = [r["_best"] for r in records
           if r.get("weighting") == "rba" and r["_best"] is not None]
    if rba:
        numbers["PinnRbaBestErr"] = fmt_err(min(rba))
    return numbers


def full_results_table(pinn, ablation, out):
    """Every run in the study, for the appendix.

    The main tables show slices chosen to make a point. This one hides nothing:
    one row per completed run, so a reader can check any cell of any other table
    against it. It lives in the appendix, which does not count toward the page
    limit.
    """
    rows = []
    for r in pinn:
        rows.append((r["_material"], ARCH_LABEL.get(r["model_type"], r["model_type"]),
                     variant_of(r), "hard" if r.get("use_ansatz") else "soft",
                     r["_best"]))
    for r in ablation:
        rows.append((r["_material"], ARCH_LABEL.get(r["model_type"], r["model_type"]),
                     {"plain": "no causal, no GN", "nocaus": "no causal",
                      "nogn": "no GradNorm", "both": "base"}[variant_key(r)],
                     "hard" if r.get("use_ansatz") else "soft", r["_best"]))
    rows = [r for r in rows if r[4] is not None]
    order = {m: i for i, m in enumerate(MATERIALS)}
    rows.sort(key=lambda r: (order.get(r[0], 9), r[1], r[2], r[3]))

    lines = [
        "% generated by make_tables.py -- do not edit",
        "\\begin{longtable}{llllr}",
        "\\caption{Every run in the study: "
        f"{len(rows)} completed runs, one row each. Relative $L^2$ (\\%) against "
        "the finite-difference reference, taking the better of the Adam and "
        "L-BFGS checkpoints. \\emph{hard} is the constraint ansatz, \\emph{soft} "
        "the IC loss.}\\\\",
        "\\label{tab:allruns}\\\\",
        "\\toprule",
        "material & architecture & arm & IC & rel $L^2$ (\\%) \\\\",
        "\\midrule",
        "\\endfirsthead",
        "\\multicolumn{5}{l}{\\small\\itshape Table~\\ref{tab:allruns}, continued}\\\\",
        "\\toprule",
        "material & architecture & arm & IC & rel $L^2$ (\\%) \\\\",
        "\\midrule",
        "\\endhead",
        "\\midrule",
        "\\multicolumn{5}{r}{\\small\\itshape continued on the next page}\\\\",
        "\\endfoot",
        "\\bottomrule",
        "\\endlastfoot",
    ]
    last_mat = None
    for mat, arch, arm, ic, err in rows:
        shown = mat if mat != last_mat else ""
        last_mat = mat
        arm_tex = arm.replace("_", "\\_").replace("+", " + ")
        lines.append(f"{shown} & {arch} & {arm_tex} & {ic} & {fmt_err(err)} \\\\")
    lines += ["\\end{longtable}", ""]
    (out / "all_runs.tex").write_text("\n".join(lines))
    return {"AllRunCount": str(len(rows))}


def frontier_stats(pinn_root):
    """How far the causal frontier got, across every run that uses one.

    The stall is the paper's mechanism, so it needs a count rather than an
    anecdote: how many runs opened all their slabs, how many opened one, and
    what each group's error looks like. RBA runs are excluded -- they replace
    the schedule and record a single slab, so they have no frontier.
    """
    import statistics
    root = Path(pinn_root)
    complete, stalled, only_one, max_opened = [], [], 0, 0
    for path in root.rglob("l2_errors.json"):
        rec = json.loads(path.read_text())
        if not rec.get("use_ansatz") or rec.get("weighting") == "rba":
            continue
        cc = path.parent / "causal_convergence.json"
        if not cc.exists():
            continue
        snaps = json.loads(cc.read_text()).get("chunk_snapshots") or []
        if not snaps or len(snaps[0][1]) < 2:
            continue
        final = snaps[-1][1]
        opened = sum(1 for w in final if w > 0)
        max_opened = max(max_opened, opened)
        vals = [rec[k] for k in ("relative_l2_error_best_lbfgs_percent",
                                 "relative_l2_error_best_adam_percent")
                if rec.get(k) is not None]
        if not vals:
            continue
        (complete if opened == len(final) else stalled).append(min(vals))
        if opened == 1:
            only_one += 1

    numbers = {}
    total = len(complete) + len(stalled)
    if not total:
        return numbers
    numbers["FrontierTotal"] = str(total)
    numbers["FrontierStalled"] = str(len(stalled))
    numbers["FrontierComplete"] = str(len(complete))
    numbers["FrontierOneSlab"] = str(only_one)
    numbers["FrontierMaxOpened"] = str(max_opened)
    if stalled:
        numbers["FrontierStalledMedian"] = fmt_err(statistics.median(stalled))
    if complete:
        numbers["FrontierCompleteBest"] = fmt_err(min(complete))
    return numbers


def variant_key(rec):
    """Which of the four weighting configurations a run belongs to."""
    gn = bool(rec.get("use_gradnorm", True))
    chunks = rec.get("causal_n_chunks", 16)
    if gn and chunks > 1:
        return "both"
    if chunks > 1:
        return "nogn"
    return "nocaus" if gn else "plain"


def ablation_table(records, baseline, out):
    """Ablation grid. `baseline` supplies the both-on column from the main
    sweep, so the published recipe is not re-run just to be compared against."""
    numbers = {}
    key = {}
    for r in baseline:
        if r.get("use_ansatz") and variant_of(r) == "base":
            key[(r["model_type"], r["_material"], "both")] = r
    for r in records:
        key[(r["model_type"], r["_material"], variant_key(r))] = r
    if not key:
        (out / "ablation.tex").write_text(
            "% no ablation results yet -- rerun make_tables.py\n")
        return numbers

    variants = ("both", "nogn", "nocaus", "plain")
    header = {"both": "causal+GradNorm", "nogn": "GradNorm off",
              "nocaus": "causal off", "plain": "both off"}
    lines = [
        "% generated by make_tables.py -- do not edit",
        "\\begin{table}[t]",
        "\\centering",
        "\\caption{Switching off the two adaptive weighting schemes, "
        "hard-constraint IC. Relative $L^2$ (\\%) at the better reported Adam "
        "or L-BFGS checkpoint; "
        "\\emph{causal+GradNorm} is the published recipe and \\emph{both off} "
        "removes both adaptive schemes.}",
        "\\label{tab:ablation}",
        "\\small",
        "\\begin{tabular}{ll" + "r" * len(variants) + "}",
        "\\toprule",
        "material & architecture & "
        + " & ".join(header[v] for v in variants) + " \\\\",
        "\\midrule",
    ]
    improvements = []
    for mat in MATERIALS:
        first = True
        for arch in ARCH_ORDER:
            cells, vals = [], {}
            for v in variants:
                r = key.get((arch, mat, v))
                vals[v] = r["_best"] if r else None
                cells.append(fmt_err(vals[v]))
            if all(c == "--" for c in cells):
                continue
            # Bold the winner only once there is something to win against --
            # a lone baseline entry is not a result.
            present = {v: x for v, x in vals.items() if x is not None}
            if len(present) > 1:
                win = min(present, key=present.get)
                cells[variants.index(win)] = \
                    "\\textbf{" + cells[variants.index(win)] + "}"
            if vals["both"] and vals["plain"]:
                improvements.append(vals["both"] / vals["plain"])
            label = mat if first else ""
            first = False
            lines.append(f"{label} & {ARCH_LABEL[arch]} & "
                         + " & ".join(cells) + " \\\\")
        if not first and mat != MATERIALS[-1]:
            lines.append("\\midrule")
    lines += ["\\bottomrule", "\\end{tabular}", "\\end{table}", ""]
    (out / "ablation.tex").write_text("\n".join(lines))

    if improvements:
        improvements.sort()
        numbers["AblMedianGain"] = f"{improvements[len(improvements) // 2]:.0f}"
        numbers["AblMinGain"] = f"{improvements[0]:.1f}"
        numbers["AblMaxGain"] = f"{improvements[-1]:.0f}"
        numbers["AblPairCount"] = str(len(improvements))
        numbers["AblWins"] = str(sum(1 for g in improvements if g > 1))
    plains = [r["_best"] for r in records
              if variant_key(r) == "plain" and r["_best"] is not None]
    if plains:
        numbers["AblBestErr"] = fmt_err(min(plains))
    return numbers


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--classical", default="results/classical/classical_benchmark.json")
    p.add_argument("--pinn", default="results/pinn")
    p.add_argument("--ablation", default="results/pinn_ablation")
    p.add_argument("--outdir", default="paper/neurips2026_workshop/tables")
    a = p.parse_args()

    out = Path(a.outdir)
    out.mkdir(parents=True, exist_ok=True)
    numbers = {}

    cpath = Path(a.classical)
    if cpath.exists():
        numbers.update(classical_tables(json.loads(cpath.read_text()), out))
        print("classical tables written")
    else:
        print(f"WARNING: {cpath} missing; classical tables not generated")

    pinn = load_pinn(a.pinn)
    print(f"{len(pinn)} PINN runs found under {a.pinn}")
    numbers.update(pinn_tables(pinn, out))

    abl = load_pinn(a.ablation)
    print(f"{len(abl)} ablation runs found under {a.ablation}")
    numbers.update(ablation_table(abl, pinn, out))
    numbers.update(frontier_stats(a.pinn))
    numbers.update(full_results_table(pinn, abl, out))
    if "AblBestErr" in numbers and "FDRefErr" in numbers:
        numbers["AblVsFDRatio"] = (
            f"{float(numbers['AblBestErr']) / float(numbers['FDRefErr']):.1f}"
        )

    macros = ["% generated by make_tables.py -- do not edit"]
    for k, v in sorted(numbers.items()):
        macros.append(f"\\newcommand{{\\{k}}}{{{v}}}")
    (out / "numbers.tex").write_text("\n".join(macros) + "\n")
    print("wrote", out / "numbers.tex")
    for k, v in sorted(numbers.items()):
        print(f"  {k:22s} {v}")


if __name__ == "__main__":
    main()
