"""Fill the NeurIPS checklist answers in place.

The checklist ships with 16 \\answerTODO{} / \\justificationTODO{} pairs and an
instruction block that the template tells you to delete. This substitutes the
answers question by question, keyed on the question heading, so re-running the
script after the upstream checklist changes will fail loudly on a heading it
does not recognise rather than silently mis-assigning an answer.

    python paper/neurips2026_workshop/fill_checklist.py
"""
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent

ANSWERS = {
    "Claims": (
        "Yes",
        "The abstract and Section~1 state the two measured claims -- that "
        "switching off causal weighting and GradNorm improves relative $L^2$ by "
        "$\\AblMinGain$--$\\AblMaxGain\\times$ on this problem, and that the "
        "second-order classical schemes plateau at $\\FDFloor\\%$ because of "
        "their absorbing boundary -- and both are supported by "
        "Tables~\\ref{tab:ablation} and~\\ref{tab:classical} respectively. The "
        "abstract also states explicitly that the ablation does not make PINNs "
        "competitive with the classical baseline.",
    ),
    "Limitations": (
        "Yes",
        "Section~\\ref{sec:discussion} ends with a Limitations paragraph "
        "covering the single seed per configuration, the 1D forward-only "
        "setting, the untuned per-architecture hyperparameters, the shared GPU "
        "the network timings were measured on, and the dependence of the "
        "causal-stall diagnosis on this particular initial condition.",
    ),
    "Theory assumptions and proofs": (
        "NA",
        "The paper contains no theoretical results; every claim is empirical.",
    ),
    "Experimental result reproducibility": (
        "Yes",
        "Appendix~\\ref{app:repro} gives the exact commands, the run-id scheme, "
        "and the complete hyperparameter set, which is identical across every "
        "architecture and arm. Appendix~\\ref{app:impl} documents the three "
        "implementation choices (the velocity--stress formulation, the "
        "resampling scheme, and continuation-state handoff) that materially "
        "change the reported numbers.",
    ),
    "Open access to data and code": (
        "Yes",
        "All code is in the accompanying repository, including the three "
        "classical solvers, the training runner with the ablation flags, and "
        "the scripts that regenerate every table, figure and inline number in "
        "this paper from the result files. There is no external dataset: the "
        "problem is a PDE with an analytic initial condition, so all data is "
        "generated by the solvers themselves.",
    ),
    "Experimental setting/details": (
        "Yes",
        "Section~\\ref{sec:pinn} gives the loss, both weighting schemes, the "
        "two initial-condition treatments and the two-phase optimiser schedule; "
        "Appendix~\\ref{app:repro} gives the collocation grid, step budgets, "
        "learning rate, causal and GradNorm settings, per-architecture sizes, "
        "and the model-selection criterion. Hyperparameters were not tuned per "
        "architecture, which is stated as a limitation.",
    ),
    "Experiment statistical significance": (
        "No",
        "Each configuration is a single run at a fixed seed, so no error bars "
        "are reported; this is stated in the Limitations paragraph. The claim "
        "the paper rests on is an order-of-magnitude effect "
        "($\\AblMinGain$--$\\AblMaxGain\\times$) that is consistent in sign "
        "across every architecture and material measured, and the accompanying "
        "mechanism (Figure~\\ref{fig:causal}) is a deterministic property of "
        "the schedule rather than a stochastic outcome. Differences of a few "
        "percent between neighbouring configurations are explicitly described "
        "as not meaningful.",
    ),
    "Experiments compute resources": (
        "Yes",
        "Section~\\ref{sec:results} and Appendix~\\ref{app:repro} report both "
        "sides: the classical solvers are single-core CPU with per-run seconds "
        "in Table~\\ref{tab:classical}, and the network runs are on NVIDIA "
        "H100 NVL GPUs with the measured wall-clock spread quoted in the text "
        "and plotted in Figure~\\ref{fig:cost}. The Limitations paragraph notes "
        "that the GPU was shared with other tenants, so network timings are "
        "upper bounds.",
    ),
    "Code of ethics": (
        "Yes",
        "The work is a numerical study of PDE solvers using synthetic data. It "
        "involves no human subjects, no personal data, and no released model or "
        "dataset artefact.",
    ),
    "Broader impacts": (
        "NA",
        "The paper is a methodological comparison of numerical and "
        "neural-network solvers for a classical PDE. It introduces no "
        "deployable system and has no direct societal application; the one "
        "practical consequence -- that a training diagnostic should be reported "
        "alongside final errors -- is discussed in "
        "Section~\\ref{sec:discussion}.",
    ),
    "Safeguards": (
        "NA",
        "The paper releases no model, dataset, or scraped content that carries "
        "a risk of misuse.",
    ),
    "Licenses for existing assets": (
        "Yes",
        "The methods reimplemented here (causal weighting, GradNorm, "
        "residual-based attention, SOAP, and each architecture) are cited to "
        "their original publications in Section~\\ref{sec:pinn}. The software "
        "used -- JAX and Equinox -- is cited and used under its own open-source "
        "licence. No third-party dataset is used.",
    ),
    "New assets": (
        "NA",
        "The paper introduces no new dataset or pretrained model. The code that "
        "produces the results is documented in Appendix~\\ref{app:repro} but is "
        "a means of reproducing the study rather than a released asset.",
    ),
    "Crowdsourcing and research with human subjects": (
        "NA",
        "The paper involves no crowdsourcing and no human subjects.",
    ),
    "Institutional review board (IRB) approvals or equivalent for research with human subjects": (
        "NA",
        "The paper involves no human subjects, so no IRB review was required.",
    ),
    "Declaration of LLM usage": (
        "NA",
        "Large language models were not part of the research method. The "
        "contributions -- the classical solver implementations, the training "
        "ablation, and the analysis -- do not involve an LLM as a component.",
    ),
}

INSTRUCTION_START = "%%% BEGIN INSTRUCTIONS %%%"
INSTRUCTION_END = "%%% END INSTRUCTIONS %%%"


def main():
    path = HERE / "checklist.tex"
    text = path.read_text(encoding="utf-8")

    # The template instructs: delete the instruction block, keep the heading.
    start, end = text.find(INSTRUCTION_START), text.find(INSTRUCTION_END)
    if start != -1 and end != -1:
        text = text[:start] + text[end + len(INSTRUCTION_END):]

    # Split on question headings so an answer can only land in its own item.
    pattern = re.compile(r"\\item \{\\bf ([^}]+)\}")
    matches = list(pattern.finditer(text))
    if len(matches) != len(ANSWERS):
        print(f"expected {len(ANSWERS)} questions, found {len(matches)}",
              file=sys.stderr)
        for m in matches:
            print("  -", m.group(1), file=sys.stderr)
        return 1

    out, cursor, filled = [], 0, 0
    for i, m in enumerate(matches):
        heading = m.group(1)
        block_end = matches[i + 1].start() if i + 1 < len(matches) else len(text)
        out.append(text[cursor:m.start()])
        block = text[m.start():block_end]
        if heading not in ANSWERS:
            print(f"no answer prepared for: {heading}", file=sys.stderr)
            return 1
        answer, justification = ANSWERS[heading]
        new = block.replace(
            "\\answerTODO{} % Replace by \\answerYes{}, \\answerNo{}, or \\answerNA{}.",
            f"\\answer{answer}{{}}")
        new = new.replace("\\answerTODO{}", f"\\answer{answer}{{}}")
        if "\\justificationTODO{}" in new:
            new = new.replace("\\justificationTODO{}", justification)
            filled += 1
        out.append(new)
        cursor = block_end
    out.append(text[cursor:])

    path.write_text("".join(out), encoding="utf-8")
    remaining = path.read_text(encoding="utf-8").count("TODO")
    print(f"filled {filled} of {len(ANSWERS)} answers; {remaining} TODO left")
    return 0 if remaining == 0 else 1


if __name__ == "__main__":
    raise SystemExit(main())
